import { useCallback, useEffect, useMemo, useState } from 'react'
import PropTypes from 'prop-types'
import { useTranslation } from 'react-i18next'
import { activateProviderRoutingConfiguration, createProviderRoutingConfiguration, deleteProviderRoutingConfiguration, fetchProviderRouting, reorderProviderFallbacks, testProviderRoutingConfiguration } from '../../api/adminApi.js'

const icons = { researcher: '⌕', writer: '✎', image: '◈', video: '▷', publisher: '↗', email: '✉', planner: '◇', general_chat: '✦' }
const text = { en: { title: 'AI Providers & Agent Routing', sub: 'Providers must be verified before activation. Keys are encrypted and never returned to the browser.', add: 'Add provider configuration', routing: 'Agent routing', catalog: 'Provider catalog', activity: 'Activity', configure: 'Configure', test: 'Test', primary: 'Set primary', fallback: 'Add fallback', remove: 'Delete', verified: 'Verified', failed: 'Failed', draft: 'Not configured', noRoute: 'No verified provider is configured for this category.', save: 'Save draft', cancel: 'Cancel', category: 'Agent category', provider: 'Provider', model: 'Model', key: 'API key', password: 'Confirm administrator password', fallbacks: 'Fallbacks', security: 'API keys are encrypted at rest and are never returned after saving.' }, ar: { title: 'مزودو الذكاء ومسارات الوكلاء', sub: 'يجب التحقق من المزود قبل التفعيل. المفاتيح مشفرة ولا تظهر في المتصفح.', add: 'إضافة إعداد مزود', routing: 'مسارات الوكلاء', catalog: 'كتالوج المزودين', activity: 'النشاط', configure: 'إعداد', test: 'اختبار', primary: 'تفعيل أساسي', fallback: 'إضافة بديل', remove: 'حذف', verified: 'تم التحقق', failed: 'فشل', draft: 'غير مهيأ', noRoute: 'لا يوجد مزود تم التحقق منه لهذه الفئة.', save: 'حفظ المسودة', cancel: 'إلغاء', category: 'فئة الوكيل', provider: 'المزود', model: 'النموذج', key: 'مفتاح API', password: 'تأكيد كلمة مرور المدير', fallbacks: 'بدائل', security: 'يتم تشفير مفاتيح API ولا تعاد إلى المتصفح بعد الحفظ.' } }

export default function AdminProvidersPage() {
  const { i18n } = useTranslation(); const rtl = i18n.dir() === 'rtl'; const t = text[rtl ? 'ar' : 'en']
  const [data, setData] = useState(); const [tab, setTab] = useState('routing'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [modal, setModal] = useState(false); const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ category_key: 'writer', provider_key: 'gemini', model_key: 'gemini-3.7-flash', api_key: '', base_url: '' })
  const [testState, setTestState] = useState('')
  const load = useCallback(async () => { try { setError(''); setData(await fetchProviderRouting()) } catch (e) { setError(e.response?.data?.message || 'Unable to load the provider control plane.') } }, [])
  useEffect(() => { load() }, [load])
  const providers = useMemo(() => data?.providers?.filter((p) => p.capabilities.includes(form.category_key) || (p.capabilities.includes('text') && ['researcher','writer','publisher','email','planner','general_chat'].includes(form.category_key))) || [], [data, form.category_key])
  const selected = providers.find((p) => p.provider_key === form.provider_key) || providers[0]
  function configure(category = 'writer', providerKey = 'gemini') { const candidate = data?.providers?.find((p) => p.provider_key === providerKey) || data?.providers?.find((p) => p.provider_key === 'gemini') || data?.providers?.[0]; setForm({ category_key: category, provider_key: candidate?.provider_key || '', model_key: candidate?.models?.[0] || '', api_key: '', base_url: '' }); setTestState(''); setModal(true) }
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); setTestState('Saving configuration…'); try { const configuration = await createProviderRoutingConfiguration(form); setForm((current) => ({ ...current, api_key: '' })); setTestState('Testing Gemini connection…'); const result = await testProviderRoutingConfiguration(configuration.id); if (result.configuration.status === 'verified') { setNotice(`Gemini connection verified successfully. Provider: Google Gemini. Model: ${configuration.model_key}. Status: Ready to activate.`); setModal(false) } else { setError(result.configuration.message || 'Connection test failed. You can fix the key and test again.'); setModal(false) } await load() } catch (err) { setError(err.response?.data?.message || 'Could not save configuration.') } finally { setTestState(''); setBusy(false) } }
  async function runAction(configuration, action, category) { setBusy(true); try { if (action === 'test') { const result = await testProviderRoutingConfiguration(configuration.id); setNotice(result.configuration.status === 'verified' ? 'Connection verified.' : result.configuration.message || 'Connection test failed.') } else if (action === 'delete') { await deleteProviderRoutingConfiguration(configuration.id); setNotice('Configuration deleted.') } else { await activateProviderRoutingConfiguration(configuration.id, { category_key: category.key, as_fallback: action === 'fallback' }); setNotice(action === 'fallback' ? 'Fallback activated.' : 'Primary route activated.') } await load() } catch (err) { setError(err.response?.data?.message || 'Action could not be completed.') } finally { setBusy(false) } }
  async function testAll() { const active = data.categories.flatMap((category) => category.routes.filter((route) => route.is_active).map((route) => route.configuration)); setBusy(true); try { await Promise.all(active.map((configuration) => testProviderRoutingConfiguration(configuration.id))); setNotice(`${active.length} active configuration(s) tested.`); await load() } catch (err) { setError(err.response?.data?.message || 'One or more provider tests failed.') } finally { setBusy(false) } }
  async function move(category, routes, index, delta) { const target = index + delta; if (target < 0 || target >= routes.length) return; const next = [...routes]; [next[index], next[target]] = [next[target], next[index]]; try { await reorderProviderFallbacks(category.id, next.map((route) => route.id)); await load() } catch (err) { setError(err.response?.data?.message || 'Could not update fallback order.') } }
  const health = data && { active: data.categories.filter((c) => c.primary?.is_active).length, attention: data.categories.filter((c) => !c.primary?.is_active).length, failed: data.configurations.filter((c) => c.status === 'failed').length }
  const routedConfigurationIds = useMemo(() => new Set(data?.categories?.flatMap((category) => category.routes.map((route) => route.configuration.id)) || []), [data])
  const pendingConfigurations = data?.configurations?.filter((configuration) => !routedConfigurationIds.has(configuration.id)) || []
  return <main className="workspace-page provider-routing-page" dir={rtl ? 'rtl' : 'ltr'}>
    <header className="provider-routing-header"><div><span className="eyebrow">ADMINISTRATION</span><h1>{t.title}</h1><p>{t.sub}</p></div><div className="provider-header-actions"><button disabled={busy} className="button button-quiet" onClick={testAll}>Test all active</button><button disabled={busy} className="button button-primary" onClick={() => configure()}>{t.add}</button></div></header>
    {health && <div className="provider-health-strip"><span><b>{health.active}</b> active & healthy</span><span><b>{health.attention}</b> needs attention</span><span><b>{health.failed}</b> failed</span><small>Last health check: {new Date(data.health_checked_at).toLocaleString()}</small></div>}
    {error && <div className="alert alert-danger">{error}</div>}{notice && <div className="alert alert-success">{notice}</div>}
    {pendingConfigurations.length > 0 && <section className="card provider-pending-configurations"><h2>Saved provider configurations</h2><p>Test each configuration, then activate a verified configuration for its selected agent category.</p>{pendingConfigurations.map((configuration) => <div className="route-line" key={configuration.id}><div><span className={`badge ${configuration.status === 'verified' ? 'badge-success' : configuration.status === 'failed' ? 'badge-danger' : 'badge-secondary'}`}>{configuration.status}</span><strong>{configuration.provider_name}</strong><small>{configuration.category_name} · {configuration.model_key} · {configuration.masked_credentials}</small>{configuration.message && <em>{configuration.message}</em>}</div><div className="route-actions"><button disabled={busy} className="button button-small button-quiet" onClick={() => runAction(configuration, 'test', { key: configuration.category_key })}>{configuration.status === 'failed' ? 'Fix & Test Again' : 'Test Connection'}</button>{configuration.status === 'verified' && <button disabled={busy} className="button button-small button-primary" onClick={() => runAction(configuration, 'primary', { key: configuration.category_key })}>Activate as Primary</button>}<button disabled={busy} className="button button-small button-danger" onClick={() => runAction(configuration, 'delete', { key: configuration.category_key })}>{t.remove}</button></div></div>)}</section>}
    <div className="provider-tabs"><button className={tab === 'routing' ? 'is-active' : ''} onClick={() => setTab('routing')}>{t.routing}</button><button className={tab === 'catalog' ? 'is-active' : ''} onClick={() => setTab('catalog')}>{t.catalog}</button><button className={tab === 'activity' ? 'is-active' : ''} onClick={() => setTab('activity')}>{t.activity}</button></div>
    {!data ? <div className="card loading-card">Loading…</div> : tab === 'routing' ? <section className="agent-routing-grid">{data.categories.map((category) => <article className="card agent-route-card" key={category.key}><div className="agent-route-heading"><span className="agent-route-icon">{icons[category.key]}</span><div><h2>{rtl ? category.name_ar : category.name}</h2><p>{category.purpose}</p></div><button className="button button-small button-quiet" onClick={() => configure(category.key)}>{t.configure}</button></div>{category.primary ? <Route item={category.primary} category={category} text={t} action={runAction} busy={busy} /> : <p className="provider-empty">{t.noRoute}</p>}<div className="fallback-list"><span>{t.fallbacks}: {category.fallback_count}</span>{category.routes.filter((route) => !route.is_primary).map((route, i, all) => <div className="fallback-row" key={route.id}><Route item={route} category={category} text={t} action={runAction} busy={busy} /><button aria-label="Move fallback up" disabled={i === 0} onClick={() => move(category, all, i, -1)}>↑</button><button aria-label="Move fallback down" disabled={i === all.length - 1} onClick={() => move(category, all, i, 1)}>↓</button></div>)}</div></article>)}</section> : tab === 'catalog' ? <section className="provider-catalog-grid">{data.providers.map((provider) => <article className="card provider-catalog-card" key={provider.provider_key}><h2>{provider.provider_name}</h2><p className="providers-kicker">{provider.provider_key}</p><div className="capability-tags">{provider.capabilities.map((cap) => <span key={cap}>{cap}</span>)}</div><p>{provider.connection_test_supported ? 'Connection test supported' : 'Requires official execution adapter'}</p><button className="button button-small button-primary" onClick={() => configure('writer', provider.provider_key)}>{t.configure}</button></article>)}</section> : <section className="card provider-activity"><h2>{t.activity}</h2><p>Configuration, connection-test, activation, fallback priority, and deletion events are retained without API keys.</p>{data.activity?.length ? <ul className="provider-audit-list">{data.activity.map((event, index) => <li key={`${event.event}-${index}`}><strong>{event.event}</strong><span>{event.category_name || 'Platform'} · {event.admin_name || 'Administrator'} · {new Date(event.created_at).toLocaleString()}</span></li>)}</ul> : <p>No provider activity recorded yet.</p>}</section>}
    {modal && <div className="modal-backdrop"><form className="modal-card card provider-config-modal" onSubmit={submit}><h2>{t.add}</h2><p>{t.security}</p><label>{t.category}<select className="input" value={form.category_key} onChange={(e) => configure(e.target.value, form.provider_key)}>{data.categories.map((c) => <option key={c.key} value={c.key}>{rtl ? c.name_ar : c.name}</option>)}</select></label><label>{t.provider}<select className="input" value={form.provider_key} onChange={(e) => { const p = providers.find((x) => x.provider_key === e.target.value); setForm({ ...form, provider_key: e.target.value, model_key: p?.models?.[0] || '' }) }}>{providers.map((p) => <option key={p.provider_key} value={p.provider_key}>{p.provider_name}</option>)}</select></label><label>{t.model}<select className="input" value={form.model_key} onChange={(e) => setForm({ ...form, model_key: e.target.value })}>{selected?.models?.map((m) => <option key={m} value={m}>{m}</option>)}</select></label><label>{form.provider_key === 'gemini' ? 'Gemini API Key' : t.key}<input className="input" required type="password" autoComplete="off" placeholder={form.provider_key === 'gemini' ? 'Paste your Gemini API key' : undefined} value={form.api_key} onChange={(e) => setForm({ ...form, api_key: e.target.value })} /></label>{form.provider_key !== 'gemini' && <label>Base URL (optional)<input className="input" type="url" value={form.base_url} onChange={(e) => setForm({ ...form, base_url: e.target.value })} /></label>}{testState && <p className="provider-test-state" role="status">{testState}</p>}<div className="modal-actions"><button type="button" disabled={busy} className="button button-quiet" onClick={() => setModal(false)}>{t.cancel}</button><button disabled={busy} className="button button-primary">{busy ? 'Testing…' : 'Save & Test Connection'}</button></div></form></div>}
  </main>
}

function Route({ item, category, text, action, busy }) { const c = item.configuration; const state = c.status === 'verified' ? text.verified : c.status === 'failed' ? text.failed : text.draft; return <div className="route-line"><div><span className={`badge ${c.status === 'verified' ? 'badge-success' : c.status === 'failed' ? 'badge-danger' : 'badge-secondary'}`}>{state}</span><strong>{c.provider_name}</strong><small>{c.model_key}{c.verified_at ? ` · ${new Date(c.verified_at).toLocaleString()}` : ''}</small>{c.message && <em>{c.message}</em>}</div><div className="route-actions"><button disabled={busy} className="button button-small button-quiet" onClick={() => action(c, 'test', category)}>{text.test}</button>{c.status === 'verified' && !item.is_primary && <button disabled={busy} className="button button-small button-primary" onClick={() => action(c, 'primary', category)}>{text.primary}</button>}{c.status === 'verified' && item.is_primary && <button disabled={busy} className="button button-small button-quiet" onClick={() => action(c, 'fallback', category)}>{text.fallback}</button>}<button disabled={busy} className="button button-small button-danger" onClick={() => action(c, 'delete', category)}>{text.remove}</button></div></div> }

Route.propTypes = {
  item: PropTypes.shape({ id: PropTypes.number, is_primary: PropTypes.bool, configuration: PropTypes.shape({ id: PropTypes.number, status: PropTypes.string, provider_name: PropTypes.string, model_key: PropTypes.string, verified_at: PropTypes.string, message: PropTypes.string }).isRequired }).isRequired,
  category: PropTypes.shape({ key: PropTypes.string }).isRequired,
  text: PropTypes.shape({ verified: PropTypes.string, failed: PropTypes.string, draft: PropTypes.string, test: PropTypes.string, primary: PropTypes.string, fallback: PropTypes.string, remove: PropTypes.string }).isRequired,
  action: PropTypes.func.isRequired,
  busy: PropTypes.bool.isRequired,
}
