"""Distribute generated content and links with safe previews and idempotency."""

import hashlib
import re
from email.message import EmailMessage
from pathlib import Path
from typing import Any

from app.agents.base import AgentExecution, BaseAgent, validation_error
from app.domain import AgentArtifact, ExecutionContext, ExecutionError
from app.providers.contracts import EmailMessageInput, EmailProvider
from app.services.idempotency import IdempotencyStore

EMAIL_PATTERN = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


class EmailAgent(BaseAgent):
    agent_type = "email"
    input_schema = "publication URL or generated Writer content"
    output_schema = "delivery result and RFC 822 preview"

    def __init__(
        self,
        artifact_root: Path,
        email_provider: EmailProvider,
        idempotency_store: IdempotencyStore,
    ) -> None:
        self.artifact_root = artifact_root.resolve()
        self.email_provider = email_provider
        self.idempotency_store = idempotency_store

    def validate_config(self, config: dict[str, Any], node_id: str) -> list[ExecutionError]:
        recipients = config.get("recipients")
        if not isinstance(recipients, list) or not 1 <= len(recipients) <= 50:
            return [
                validation_error(
                    "invalid_config",
                    "Email requires between 1 and 50 recipients.",
                    node_id,
                    self.agent_type,
                    field="recipients",
                )
            ]
        invalid = [
            value
            for value in recipients
            if not isinstance(value, str) or not EMAIL_PATTERN.fullmatch(value) or len(value) > 254
        ]
        if invalid:
            return [
                validation_error(
                    "invalid_config",
                    "Email contains an invalid recipient address.",
                    node_id,
                    self.agent_type,
                    field="recipients",
                )
            ]
        subject = config.get("subject")
        if (
            not isinstance(subject, str)
            or not subject.strip()
            or len(subject) > 998
            or "\n" in subject
            or "\r" in subject
        ):
            return [
                validation_error(
                    "invalid_config",
                    "Email subject is required and must not contain line breaks.",
                    node_id,
                    self.agent_type,
                    field="subject",
                )
            ]
        body_template = config.get("body_template")
        if body_template is not None and (
            not isinstance(body_template, str) or len(body_template) > 20_000
        ):
            return [
                validation_error(
                    "invalid_config",
                    "Email body template must be text up to 20,000 characters.",
                    node_id,
                    self.agent_type,
                    field="body_template",
                )
            ]
        return []

    def validate_input(self, input_data: dict[str, Any], node_id: str) -> list[ExecutionError]:
        content, links = self._content(input_data)
        if not content and not links:
            return [
                validation_error(
                    "invalid_input",
                    "Email requires generated content or a publication result.",
                    node_id,
                    self.agent_type,
                )
            ]
        return []

    def execute(
        self,
        input_data: dict[str, Any],
        config: dict[str, Any],
        execution_context: ExecutionContext,
        node_id: str,
    ) -> AgentExecution:
        content, links = self._content(input_data)
        template = str(config.get("body_template") or "{content}\n\n{links}")
        body = template.replace("{content}", content).replace("{links}", "\n".join(links)).strip()
        if not body:
            body = "Generated by Nasaq AI."
        idempotency_key = f"{execution_context.workflow_run_id}:{node_id}"
        message = EmailMessageInput(
            recipients=[str(value).strip() for value in config["recipients"]],
            subject=str(config["subject"]).strip(),
            text_body=body,
            idempotency_key=idempotency_key,
        )
        preview = self._preview(message, execution_context, node_id)
        payload, reused = self.idempotency_store.execute_once(
            idempotency_key,
            lambda: self.email_provider.send(message, execution_context.user_id).model_dump(
                mode="json"
            ),
        )
        warnings = []
        if payload["simulated"]:
            warnings.append("DEMO MODE: email delivery was simulated; no message was sent.")
        if reused:
            warnings.append("A completed delivery was reused; no duplicate email was sent.")
        return AgentExecution(
            output_type="email_delivery",
            data={
                "delivery": payload,
                "message_id": payload["message_id"],
                "recipients": payload["recipients"],
                "subject": message.subject,
                "delivery_status": "simulated" if payload["simulated"] else "sent",
                "simulated": payload["simulated"],
                "preview_file": preview.model_dump(mode="json"),
                "idempotency_key": idempotency_key,
                "idempotency_reused": reused,
            },
            artifacts=[preview],
            warnings=warnings,
            provider=str(payload["provider"]),
        )

    @staticmethod
    def _content(input_data: dict[str, Any]) -> tuple[str, list[str]]:
        chunks: list[str] = []
        links: list[str] = []

        def visit(value: Any) -> None:
            if isinstance(value, dict):
                content = value.get("content")
                if isinstance(content, str) and content.strip():
                    chunks.append(content.strip())
                for key in ("url", "public_url", "share_url", "watch_url"):
                    url = value.get(key)
                    if isinstance(url, str) and url.startswith(("https://", "http://")):
                        links.append(url)
                for nested in value.values():
                    if isinstance(nested, (dict, list)):
                        visit(nested)
            elif isinstance(value, list):
                for nested in value:
                    visit(nested)

        visit(input_data)
        return "\n\n".join(dict.fromkeys(chunks)), list(dict.fromkeys(links))

    def _preview(
        self,
        message: EmailMessageInput,
        context: ExecutionContext,
        node_id: str,
    ) -> AgentArtifact:
        safe_run = (
            re.sub(r"[^A-Za-z0-9._-]+", "-", context.workflow_run_id).strip(".-") or "unknown"
        )
        safe_node = re.sub(r"[^A-Za-z0-9._-]+", "-", node_id).strip(".-") or "unknown"
        directory = self.artifact_root / safe_run[:100] / safe_node[:100]
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / "email-preview.eml"
        preview = EmailMessage()
        preview["From"] = "Nasaq AI Preview <preview@nasaq.invalid>"
        preview["To"] = ", ".join(message.recipients)
        preview["Subject"] = message.subject
        preview["X-Nasaq-Simulation"] = "preview-only"
        preview.set_content(message.text_body)
        path.write_bytes(preview.as_bytes())
        checksum = hashlib.sha256(path.read_bytes()).hexdigest()
        artifact_id = hashlib.sha256(
            f"{context.workflow_run_id}:{node_id}:email-preview".encode()
        ).hexdigest()[:24]
        return AgentArtifact(
            id=artifact_id,
            owner_id=context.user_id,
            workflow_run_id=context.workflow_run_id,
            node_id=node_id,
            path=str(path),
            storage_key=str(path.relative_to(self.artifact_root)).replace("\\", "/"),
            mime_type="message/rfc822",
            file_name=path.name,
            file_size=path.stat().st_size,
            checksum_sha256=checksum,
        )
